# B"H

name: Build and Packege

on:
  workflow_dispatch:
  push:
    branches: 
    - "*"

env:
  IMAGE: go-http-server
  REGISTRY: smuel770

jobs:
  build-publish:
    name: Build, Publish
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # helper for authentication
    - run: |-
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$REGISTRY/$IMAGE:$GITHUB_SHA" \
          --tag "$REGISTRY/$IMAGE:$GITHUB_REF_NAME" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .

    # Tag the Docker image
    - name: Tag
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |-
        docker tag \
          "$REGISTRY/$IMAGE:$GITHUB_SHA" "$REGISTRY/$IMAGE:latest"

    # Push the Docker image to Google Container Registry
    - name: Publish
      run: |-
        echo $IMAGE_DIGEST
        docker push "$REGISTRY/$IMAGE:$GITHUB_SHA"
        docker push "$REGISTRY/$IMAGE:latest"